[project]
name = "nextcoder-formatter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.0.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.0",
]
