[project]
name = "nextcoder-formatter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.0.0",
    "tree-sitter",
    "tree-sitter-languages",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.0",
]
